version: '3.8'
services:
  mysql:
    container_name: mysql8
    image: mysql:8.0.35
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/docker/volumes/mysql8/conf:/etc/mysql/conf.d
      - /var/lib/docker/volumes/mysql8/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
  nacos:
    container_name: nacos
    image: nacos/nacos-server:1.4.1
    ports:
      - "8849:8848"
    environment:
      - MODE=standalone
  rabbitmq:
    container_name: mq
    image: rabbitmq:3.8-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=itcast
      - RABBITMQ_DEFAULT_PASS=123
    hostname: mq1
  minio:
    container_name: minio
    image: bitnami/minio:2022.9.7
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /var/lib/docker/volumes/minio/data:/bitnami/minio/data
  redis:
    container_name: redis
    image: redis:6.2.7
    ports:
      - "6379:6379"
    command:
      - redis-server
  nginx:
    container_name: nginx
    image: nginx:1.12.2
    ports:
      - "80:80"
    volumes:
      - /var/lib/docker/volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/lib/docker/volumes/nginx/html:/usr/share/nginx/html:ro
  xxl-job-admin:
    container_name: xxl-job-admin
    image: xuxueli/xxl-job-admin:2.3.1
    ports:
      - "8088:8080"
    volumes:
      - /var/lib/docker/volumes/xxl-job-admin:/data/applogs
    environment:
      - PARAMS="--spring.datasource.url=jdbc:mysql://192.168.164.132:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=123 --spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver"
  elasticsearch:
    container_name: es
    image: elasticsearch:7.12.1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - es-plugins:/usr/share/elasticsearch/plugins
    privileged: true
    networks:
      - es-net
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
  kibana:
    container_name: kibana
    image: kibana:7.12.1
    ports:
      - "5601:5601"
    volumes:
      - /var/lib/docker/volumes/registry:/var/lib/registry
    networks:
      - es-net
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk17
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/lib/docker/volumes/jenkins/jenkins_home:/var/jenkins_home
  registry:
    container_name: registry
    image: registry
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /var/lib/docker/volumes/registry:/var/lib/registry
  docker-ui:
    container_name: docker-ui
    image: joxit/docker-registry-ui:static
    ports:
      - "8888:80"
    environment:
      - REGISTRY_TITLE=学成在线私有仓库
      - REGISTRY_URL=http://registry:5000
    depends_on:
      - registry
volumes:
  es-data:
  es-plugins:
networks:
  es-net: